apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: orderdb
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: order-db
